blueprint:
  name: 💊 Medikament Erinnerung (NFC + Warnung)
  description: >
    Medikamentenverwaltung mit Erinnerung, NFC-Auffüllen,
    Dosierung und Warnung bei niedrigem Bestand.
  domain: automation

  input:
    med_name:
      name: Medikamentenname
      selector:
        text:

    med_counter:
      name: Bestandszähler
      selector:
        entity:
          domain: counter

    dosis:
      name: Dosierung
      selector:
        entity:
          domain: input_number

    warnwert:
      name: Warnschwelle
      selector:
        entity:
          domain: input_number

    auffuellwert:
      name: NFC Auffüllwert
      selector:
        entity:
          domain: input_number

    erinnerungszeit:
      name: Einnahmezeit
      selector:
        entity:
          domain: input_datetime

    nfc_tag:
      name: NFC Tag ID
      selector:
        text:

trigger:
  - id: erinnerung
    platform: time
    at: !input erinnerungszeit

  - id: nfc
    platform: tag
    tag_id: !input nfc_tag

  - id: warnung
    platform: numeric_state
    entity_id: !input med_counter
    below: !input warnwert

mode: restart

action:
  - choose:

      ################################
      # NFC → Bestand setzen
      ################################
      - conditions:
          - condition: trigger
            id: nfc
        sequence:
          - service: counter.set_value
            target:
              entity_id: !input med_counter
            data:
              value: "{{ states(!input auffuellwert) | int }}"

          - service: notify.notify
            data:
              message: >
                💊 {{ !input med_name }} aufgefüllt auf
                {{ states(!input auffuellwert) | int }} Tabletten

      ################################
      # Warnung
      ################################
      - conditions:
          - condition: trigger
            id: warnung
        sequence:
          - service: notify.notify
            data:
              title: "⚠️ Medikament fast leer"
              message: >
                {{ !input med_name }}:
                nur noch {{ states(!input med_counter) | int }} Tabletten

      ################################
      # Erinnerung
      ################################
      - conditions:
          - condition: trigger
            id: erinnerung
        sequence:
          - service: notify.notify
            data:
              title: "💊 {{ !input med_name }}"
              message: >
                Bitte einnehmen
                ({{ states(!input dosis) | int }} Tabletten)
              data:
                actions:
                  - action: taken
                    title: "Eingenommen"
                  - action: later
                    title: "Später erinnern"

          - wait_for_trigger:
              - platform: event
                event_type: mobile_app_notification_action

          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ wait.trigger.event.data.action == 'taken' }}
                sequence:
                  - repeat:
                      count: "{{ states(!input dosis) | int }}"
                      sequence:
                        - service: counter.decrement
                          target:
                            entity_id: !input med_counter

              - conditions:
                  - condition: template
                    value_template: >
                      {{ wait.trigger.event.data.action == 'later' }}
                sequence:
                  - delay: "00:15:00"
                  - service: notify.notify
                    data:
                      message: "⏰ Erinnerung: Medikament einnehmen"
