blueprint:
  name: 💊 Medikament Erinnerung (NFC + Warnung)
  description: >
    Erinnerung zur Medikamenteneinnahme mit variabler Dosierung,
    NFC-Auffüllen auf festen Wert und Warnung bei niedrigem Bestand.
  domain: automation

  input:
    med_name:
      name: Medikamentenname
      selector:
        text:

    med_counter:
      name: Bestandszähler
      selector:
        entity:
          domain: counter

    dosis:
      name: Dosierung (Tabletten pro Einnahme)
      selector:
        entity:
          domain: input_number

    warnwert:
      name: Warnschwelle
      selector:
        entity:
          domain: input_number

    auffuellwert:
      name: Auffüllmenge (NFC)
      selector:
        entity:
          domain: input_number

    erinnerungszeit:
      name: Einnahmezeit
      selector:
        entity:
          domain: input_datetime

    nfc_tag:
      name: NFC Tag
      selector:
        text:

    notify_device:
      name: Smartphone
      selector:
        device:
          integration: mobile_app

mode: restart

trigger:
  - platform: time
    at: !input erinnerungszeit

  - platform: tag
    tag_id: !input nfc_tag

  - platform: state
    entity_id: !input med_counter

action:
  - choose:

      ################################################
      # NFC → festen Wert setzen
      ################################################
      - conditions:
          - condition: template
            value_template: "{{ trigger.platform == 'tag' }}"
        sequence:
          - service: counter.set_value
            target:
              entity_id: !input med_counter
            data:
              value: "{{ states(!input auffuellwert) | int }}"

          - service: notify.notify
            data:
              message: >
                💊 {{ !input med_name }} aufgefüllt auf
                {{ states(!input auffuellwert) | int }} Tabletten

      ################################################
      # Warnung bei niedrigem Bestand
      ################################################
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.platform == 'state' and
                 states(!input med_counter) | int
                 <= states(!input warnwert) | int }}
        sequence:
          - service: notify.notify
            data:
              title: "⚠️ Medikament fast leer"
              message: >
                {{ !input med_name }}:
                Nur noch {{ states(!input med_counter) | int }} Tabletten übrig

      ################################################
      # Erinnerung
      ################################################
      - conditions:
          - condition: template
            value_template: "{{ trigger.platform == 'time' }}"
        sequence:
          - service: notify.notify
            data:
              title: "💊 {{ !input med_name }}"
              message: >
                Bitte einnehmen
                ({{ states(!input dosis) | int }} Tabletten)
              data:
                actions:
                  - action: taken
                    title: "Eingenommen"
                  - action: later
                    title: "Später erinnern"

          - wait_for_trigger:
              - platform: event
                event_type: mobile_app_notification_action

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ wait.trigger.event.data.action == 'taken' }}"
                sequence:
                  - repeat:
                      count: "{{ states(!input dosis) | int }}"
                      sequence:
                        - service: counter.decrement
                          target:
                            entity_id: !input med_counter

              - conditions:
                  - condition: template
                    value_template: "{{ wait.trigger.event.data.action == 'later' }}"
                sequence:
                  - delay: "00:15:00"
                  - service: notify.notify
                    data:
                      message: "⏰ Erinnerung: Medikament einnehmen"
