blueprint:
  name: 💊 Medikament Erinnerung – Basis
  domain: automation
  description: Erinnerung zur Medikamenteneinnahme

  input:
    med_name:
      name: Medikamentenname
      selector:
        text:

    erinnerungszeit:
      name: Einnahmezeit
      selector:
        time:

trigger:
  - platform: time
    at: !input erinnerungszeit

action:
  - service: notify.notify
    data:
      title: "💊 Erinnerung"
      message: "Bitte Medikament einnehmen"
