blueprint:
  name: 💊 Medikament Erinnerung stabil
  domain: automation
  description: Erinnerung auf das gewählte Handy, ohne Templates

  input:
    med_name:
      name: Medikamentenname
      selector:
        text:

    erinnerungszeit:
      name: Einnahmezeit
      selector:
        time:

    notify_device:
      name: Gerät für Benachrichtigung
      selector:
        device:
          integration: mobile_app

trigger:
  - platform: time
    at: !input erinnerungszeit

action:
  - service: notify.mobile_app_{{ device_attr(!input notify_device, 'name') | lower }}
    data:
      title: "💊 Erinnerung"
      message: !input med_name
